apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  # root password: "rootpassword" -> cm9vdHBhc3N3b3Jk
  # database: "petclinic" -> cGV0Y2xpbmljaw==
  # user: "petclinic" -> cGV0Y2xpbmljaw==
  # password: "petclinic" -> cGV0Y2xpbmljaw==
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-database: cGV0Y2xpbmljaw==
  mysql-user: cGV0Y2xpbmljaw==
  mysql-password: cGV0Y2xpbmljaw==