apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: default
data:
  application.properties: |
    spring.application.name=PetClinic
    server.port=8080
    spring.jpa.database=H2