apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: default
data:
  application.properties: |
    spring.application.name=PetClinic
    spring.jpa.database=H2
    spring.h2.console.enabled=true
    server.port=8080
    logging.level.root=INFO
    logging.level.org.springframework.samples.petclinic=DEBUG